# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EnglishPremierLeague' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'Moya/Combine'
       
  target 'EnglishPremierLeagueTests' do
      inherit! :search_paths
      pod 'Moya'
      pod 'Moya/Combine'
  end

end
